### ISSUE TITLE
Google Maps Integration

### ISSUE THREAD

**Issue by jarvisteach** [jarvisteach/appJar#136]
A way to embed static google map images.

http://hci574.blogspot.co.uk/2010/04/using-google-maps-static-images.html

**Comment by jarvisteach** [comment]
Basic function added for retrieving GoogleMaps images.
Now, need to roll into a widget.

Look into adding built-in, overlaid widgets:
* zoom in/out
* change type
* home
* (maybe a search?)

**Comment by jarvisteach** [comment]
Have played a bit - can simply `place()` buttons over the image's label, relative to the size of the label.

Have also added new function `.getLocation()` to do a lookup on th eIP address, to get start place for maps

**Comment by jarvisteach** [comment]
Create a canvas, containing +/-/home button above a drop-down of types.
This should be transparent & borderless.

It can then be placed in any of the four corners, above the image:
* mapControls.place(rely=1.0, relx=1.0, x=0, y=0, anchor=SE)

**Comment by jarvisteach** [comment]
Issues on python 3.3.6

```
	Testing GoogleMaps: 3.3
Traceback (most recent call last):
  File "widget_test.py", line 1713, in <module>
    test_googlemap()
  File "widget_test.py", line 1638, in test_googlemap
    app.addImageData("gm2", data)
  File "../appJar/appjar.py", line 4788, in addImageData
    imgObj = self.__getImageData(imageData, fmt)
  File "../appJar/appjar.py", line 4639, in __getImageData
    imgObj = PhotoImage(data=imageData)
  File "/opt/python/3.3.6/lib/python3.3/tkinter/__init__.py", line 3425, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/opt/python/3.3.6/lib/python3.3/tkinter/__init__.py", line 3381, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: no image data for this index
```

**Comment by jarvisteach** [comment]
Self-contained widget now implemented.
Minimal widget testing done - need to investigate setters, containers, etc...

Need to add some additional functionality:
* ability to set start location, zoom level & terrain through appJar
* ability to query to find current displayed location, zoom level & terrain

Version 2, should have:
* ability to drop pins
* ability to export displayed map as image

Version 3, should have:
* ability to scroll - will require getting lat/long and modifying, bearing in mind zoom level
* image map to drop pins

**Comment by jarvisteach** [comment]
Beta widget now complete.
Have created new issue for version 2/3 features.
