### ISSUE TITLE
Can we get line number details in the logging output?

### ISSUE THREAD

**Issue by jarvisteach** [jarvisteach/appJar#211]
There is an inspect module:

* https://docs.python.org/2/library/inspect.html
* https://docs.python.org/3/library/inspect.html

That allows us to look back through the stack, each entry induces a line number and function name.

We can add this to the logging function (logMessage) - but need to go back a couple of function calls in order to find the line that called us.

**Comment by jarvisteach** [comment]
NB. this won't take effect if called from static classes or subclasses - should we make the logging functions static also??

**Comment by jarvisteach** [comment]
Now logs:
* [line number/function name] for appJar messages
* [line number] for external logs

Can now go through code and tidy up log messages - don't need to say function name in the message!

**Comment by jarvisteach** [comment]
Uses a loop to find first stack entry with the main program's filename.

Convinced this will break in interactive mode or something similar - need to consolidate best way for finding calling program's name, make it global & static and use everywhere...

**Comment by jarvisteach** [comment]
Indeed it does:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "appJar/appjar.py", line 432, in __init__
    self.__checkMode()
  File "appJar/appjar.py", line 629, in __checkMode
    self.warn("Interactive mode is not fully tested, some features might not work.")
  File "appJar/appjar.py", line 1499, in warn
    def warn(message): gui.logMessage(message, "WARNING")
  File "appJar/appjar.py", line 1513, in logMessage
    if str(os.path.basename(theMain.__file__)) in s[1]:
```
