### ISSUE TITLE
NameError: name 'Widgets' is not defined: [widgets branch]

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#268]
Here's the full output.

```
>>> from appJar import gui
>>> with gui() as app:
...  app.useTtk()
...  app.addLabel('foo', 'bar')
... 
2017-10-14 12:04:53,882 appJar:WARNING [586/__checkMode]: Interactive mode is not fully tested, some features might not work.
2017-10-14 12:04:53,988 appJar:ERROR [1632/__exit__]: ContextManager: failed
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/mark/.local/lib/python3.5/site-packages/appJar/appjar.py", line 6768, in addLabel
    self.widgetManager.verify(Widgets.Label, title)
NameError: name 'Widgets' is not defined
```

**Comment by jarvisteach** [comment]
This should be fixed now (should have been referencing `self.Widgets`)

**Comment by mpmc** [comment]
@jarvisteach Yep, I noticed the commit & upgraded, now it works!
