### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#280]
As title.

```
Traceback (most recent call last):
  File "gui2.py", line 266, in <module>
    sys.exit(main(sys.argv))
  File "gui2.py", line 261, in main
    app = Gui()
  File "gui2.py", line 42, in __init__
    self.setLocation("CENTER")
  File "/home/mark/.local/lib/python3.5/site-packages/appJar/appjar.py", line 2106, in setLocation
    self.CENTER(self.__getTopLevel())
  File "/home/mark/.local/lib/python3.5/site-packages/appJar/appjar.py", line 172, in CENTER
    geom = win.geom.split("x")
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by jarvisteach** [comment]
No idea what branch you're on :)

But, having played around with some other things, there is a scenario where geom gets set to None...

**Comment by mpmc** [comment]
> No idea what branch you're on :)

I'll always use next_release unless told not to.
