### ISSUE TITLE
Padding error - e7d6c20

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#308]
```
2017-11-26 18:06:34,597 appJar:WARNING [Line 79]: Unknown function: <_gui__prepContainer> Check your spelling, do you need more camelCase?
Traceback (most recent call last):
  File "gui3.py", line 102, in <module>
    sys.exit(main(sys.argv))
  File "gui3.py", line 96, in main
    app = Gui()
  File "gui3.py", line 41, in __init__
    self.error('Mooooooooooo')
  File "gui3.py", line 80, in error
    self.widget_defaults()
  File "gui3.py", line 62, in widget_defaults
    self.setPadding(out_x, out_y)
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 2129, in setPadding
    self.containerStack[-1]['padx'] = x
TypeError: 'NoneType' object does not support item assignment
```

This is using next_release @ e7d6c20

**Comment by jarvisteach** [comment]
Urgh! So much for automated testing!

**Comment by mpmc** [comment]
@jarvisteach 

It happens!

**Comment by jarvisteach** [comment]
Hopefully resolved, and added in better testing!

**Comment by mpmc** [comment]
Yep, it's working :+1:
