### ISSUE TITLE
[next_release / 9d7a2d3] _tkinter.TclError: invalid command name ".!canvasdnd.!frame2.!tabbedframe"

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#336]
Yep, it's me again & I brokes (sic) it!

Code that generates this..

```python
    def main(self):
        """Device info and settings window."""
        # Tab name.
        tab = _('maintab')
        # Status tab title.
        status = _('Status')
        # Settings.
        settings = _('Settings')
        # Get device details.
        cache = self.controller_cache

        # Reset to defaults & start new frame.
        self.removeAllWidgets()
        self.widget_defaults()
        with self.startTabbedFrame('{}'.format(tab)):
            # Status tab.
            with self.startTab('{}'.format(status)):
                self.addLabel('test', 'testing!')
```
traceback

```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 748, in callit
    func(*args)
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 1945, in __processEventQueue
    func(*args, **kwargs)
  File "gui.py", line 113, in show
    self.removeAllWidgets()
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 3159, in removeAllWidgets
    self.__configBg(container)
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 591, in __configBg
    self.bgLabel = Label(container, anchor=CENTER, font=self.labelFont, background=self.__getContainerBg())
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 3425, in __getContainerBg
    return self.getContainer()["bg"]
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1486, in cget
    return self.tk.call(self._w, 'cget', '-' + key)
_tkinter.TclError: invalid command name ".!canvasdnd.!frame2.!tabbedframe"
```

**Comment by jarvisteach** [comment]
There's a separate (maybe related issue) with your code...

When using the context manger approach (with) there are different functions to call, so instead of `.startTabbedFrame()` & `.startTab()` you should be using `.tabbedFrame()` and `.tab()`

That might make a difference?

**Comment by mpmc** [comment]
Yep it does - I didn't think to check for changes between the release/next!
