### ISSUE TITLE
New container - side menu

### ISSUE THREAD

**Issue by jarvisteach** [jarvisteach/appJar#342]
A new container - with a menu down the left and panes on the right - similar to installation/setup screens.

This could be achieved fairly easily with a listbox and multiple frames

**Comment by mpmc** [comment]
Tried the new demo for side menu - got.

```2018-01-06 22:34:15,518 appJar:WARNING [Line 36->2573/setTransparency]: Transparency not supported on LINUX```
```python
Traceback (most recent call last):
  File "issue342.py", line 36, in <module>
    size=(600,400), sticky="news", labelFont=20, buttonFont=15, transparency=98) as app:
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 547, in __init__
    self.configure(**kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 2265, in configure
    if icon is not None: self.icon = icon
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 4998, in __setattr__
    super(gui, self).__setattr__(name, value)
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 2545, in setIcon
    container.wm_iconbitmap(image)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1868, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "favicon.ico" not defined
```

**Comment by jarvisteach** [comment]
Try removing the `icon` parameter from the main constructor, or put a copy of the favicon in the folder

**Comment by mpmc** [comment]
Yep that worked, however it doesn't play nice with ttk.

**Comment by jarvisteach** [comment]
early days :)

**Comment by jarvisteach** [comment]
![342](https://user-images.githubusercontent.com/13473435/35243541-2e25854c-ffb5-11e7-9f1b-b2eb6b590395.png)

**Comment by mpmc** [comment]
I wouldn't say this is a side menu it's more a paged side menu, especially given the previous / next buttons. A side menu would be more akin to ttk's notebook like [here](https://stackoverflow.com/questions/46909169/python-tkinter-side-notebook-tabs).

**Comment by The-Sleepy-Penguin** [comment]
I *have* noticed a small thing though - on Windows, the text in a listbox is underlined when it is active (and it appears that on Mac/Linux this doesn't happen). I feel that it makes the menu on the side a bit odd for some reason - (looks too much like a hyperlink I think).
Just thought that I'd point that out...

**Comment by jarvisteach** [comment]
The next/previous buttons just cycle through the tabs, they could be easily enabled/disabled.

I googled the underline - looks like the "activestyle" config of the listbox defaults to underlined, although you're right, I've never noticed this on a mac.

I think setting that to "none" might remove the underline...

**Comment by The-Sleepy-Penguin** [comment]
@jarvisteach Yep - that removed the underline.

**Comment by jarvisteach** [comment]
* Now uses FrameStack.
* Can now disable/enable keyboard/mouse control of tabs.
* Improved looks

![side](https://user-images.githubusercontent.com/13473435/38672348-cf95ffbe-3e45-11e8-9f93-ec1ccc71014f.png)

**Comment by jarvisteach** [comment]
Long lists add a scrollbar - ruins the colours :(
