### ISSUE TITLE
ttk breaks accessibility window

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#424]
```
Traceback (most recent call last):
  File "gui.py", line 237, in <module>
    sys.exit(main(sys.argv))
  File "gui.py", line 230, in main
    app = Gui(*args, useTtk=True)
  File "gui.py", line 46, in __init__
    self.start()
  File "gui.py", line 158, in start
    self.default()
  File "gui.py", line 226, in default
    self.button(**self.prop('accessibility'))
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 7794, in button
    elif icon is not None: button = self._buttonMaker(title, value, "icon", icon, *args, **kwargs)
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 7808, in _buttonMaker
    elif kind == "icon": return self.addIconButton(title, func, extra, row, column, colspan, rowspan, align=align)
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 7918, in addIconButton
    return self.addImageButton(title, func, icon, row, column, colspan, rowspan, align)
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 7911, in addImageButton
    self.setButtonImage(title, imgFile, align)
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 7937, in setButtonImage
    but.config(image=image, compound=TOP, text="", justify=LEFT)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1482, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1473, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-justify"
```

**Comment by jarvisteach** [comment]
I've removed justify & padding, so the GUI will start.

But accessibility won't work in ttk mode - need to update font setting to work in ttk mode.

**Comment by jarvisteach** [comment]
Closing this, as issue #385 will resolve it.
