### ISSUE TITLE
Adding label and entry error

### ISSUE THREAD

**Issue by Binxlola** [jarvisteach/appJar#478]
I have code that when a button is pressed, a label and an entry will be added to a frame. Now I finished this a little while back and tested it, and it ran smoothly. Now however when retesting some of the features of the app that same functionality produces the error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/Users/jasonsmit/PycharmProjects/Project-X/appJar/appjar.py", line 3603, in <lambda>
    return lambda *args: funcName(param)
  File "/Users/jasonsmit/PycharmProjects/Project-X/main.py", line 232, in add_column
    with app.labelFrame("New Table"):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/jasonsmit/PycharmProjects/Project-X/appJar/appjar.py", line 5100, in labelFrame
    lf.config(fg=labelFg)
AttributeError: 'NoneType' object has no attribute 'config'

At one point I did change the Gui to use settings, which may or may not have changed something in someway. I thought maybe if anyone could possibly clarify what this error message is trying to tell me?

**Comment by jarvisteach** [comment]
Hi @Binxlola - I've just had a look at this - the issue has been introduced in a recent release, but has uncovered a deeper problem. All calls to `openContainer` are return `None`, when they should be returning the container. I'll patch it now, and try to work out why it's not been picked up in testing.
