### ISSUE TITLE
Error during removeAllWidgets

### ISSUE THREAD

**Issue by jbhurst** [jarvisteach/appJar#497]
When running removeAllWdgets from either .93 or to 7/27/2018 publish, I get:

"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1542, in __call__
    return self.func(*args)
  File "g:\automation\modules\appJar\appjar.py", line 3576, in <lambda>
    return lambda *args: funcName(param)
  File "\\netvia.local\files\HomeFolders\bradyhurst\projects\vsGenesis\g\automation\modules\nvgen\forms\nvgui.py", line 616, in fileMenuPress
    self.openjob(resp)
  File "\\netvia.local\files\HomeFolders\bradyhurst\projects\vsGenesis\g\automation\modules\nvgen\forms\nvgui.py", line 1122, in openjob
    self.populategui()
  File "\\netvia.local\files\HomeFolders\bradyhurst\projects\vsGenesis\g\automation\modules\nvgen\forms\nvgui.py", line 375, in populategui
    self.app.removeAllWidgets(current=False)
  File "g:\automation\modules\appJar\appjar.py", line 3543, in removeAllWidgets
    self._configBg(container)
  File "g:\automation\modules\appJar\appjar.py", line 732, in _configBg
    self.bgLabel.place(x=0, y=0, relwidth=1, relheight=1)
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1991, in place_configure
    + self._options(cnf, kw))
TclError: bad window path name ".63706928.127723664.127723760"
"

It looks like it is failing when trying to place the background label.  I wrapped the bgLabel calls in _configBg in a try:  except: pass block and it seemed to work without adverse consequences for me.

**Comment by jarvisteach** [comment]
I'm glad you've managed to get it to work, but there are a lot more issues with that function, and you'll probably find it breaks other stuff.

I'm going to make this a priority over the next week to sort once and for all.

Starting by bringing all the issues together:
* Issue #423 is already open, waiting for a solution.
* Issue #462 also discusses this problem.

I'm going to close this issue, and merge the above two together.
