### ISSUE TITLE
 Unknown platform: CYGWIN_NT-10.0-WOW

### ISSUE THREAD

**Issue by sharuzzaman** [jarvisteach/appJar#537]
# Bug Report
---

## Context
---
I'm testing appJar with Python in Cygwin

## Expected Behaviour
---
appJar should run

## Actual Behaviour
---
appJar does not run

## Any error messages produced by appJar
---
$ ./main.py
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    app = gui()
  File "/cygdrive/c/Users/sharuzzr/Downloads/app/appJar/appjar.py", line 438, in __init__
    self.platform = gui.GET_PLATFORM()
  File "/cygdrive/c/Users/sharuzzr/Downloads/app/appJar/appjar.py", line 265, in GET_PLATFORM
    raise Exception("Unknown platform: " + platform())
Exception: Unknown platform: CYGWIN_NT-10.0-WOW

## Sample code, demonstrating the issue
---
$ cat main.py
#!/bin/env python

# import the library
from appJar import gui
# create a GUI variable called app
app = gui()

## What steps are needed to reproduce the bug
---
1. Install Cygwin
2. Install Python 2.7 package in Cygwin
3. Create main.py like above
4. ./main.py

## Version Information
---
$ python main.py -v
appJar: 0.93.0 Python: 2.7.14 TCL: 8.6, TK: 8.6 Platform: CYGWIN_NT-10.0-WOW
pid: 16036 locale: en_US

**Comment by jarvisteach** [comment]
Hi @sharuzzaman - thanks for raising this.

There are lots of platform specific sections inside appJar, trying to keep the same functionality across MAC/WINDOWS/LINUX - so, the first thing appJar does, is determine a platform.

I've not really come across CYGWIN before - I've just googled it, and it looks like a "linux emulator" running inside Windows.

So, if appJar finds CYGWIN I'll configure it to set Windows as the platform, I'm assuming all the Windows functionality will still be available?

**Comment by jarvisteach** [comment]
Difficult one, I don't have an environment right now where I can test this.

But the fix would have been to either have `GET_PLATFORM()` return `gui.LINUX' or 'gui.WINDOWS`

If both of those fail, then it's going to be a bigger problem!

**Comment by jarvisteach** [comment]
I've had a quick google, and found the following site: https://daddyathouse76.wordpress.com/2017/06/10/python-gui-on-cygwin/

Are you running an X server within CYGWIN? If not, that'll explain the no display error...

**Comment by jarvisteach** [comment]
Hi @sharuzzaman - I was wondering if this had given you any help?
