### ISSUE TITLE
_tkinter.TclError: bad cursor spec "pointinghand"

### ISSUE THREAD

**Issue by frakman1** [jarvisteach/appJar#646]
MacOS Mojave 
`appJar: 0.94.0 Python: 3.6.5 TCL: 8.6, TK: 8.6 Platform: Darwin pid: 69895`

error message:
```
~/.pyenv/shims/python3 lights.py
Traceback (most recent call last):
  File "lights.py", line 1325, in <module>
    app.startTab("Follow Desktop")
  File "/Users/frak/.pyenv/versions/3.6.5/lib/python3.6/site-packages/appJar/appjar.py", line 4937, in startTab
    tab = self.startContainer(WIDGET_NAMES.Tab, title)
  File "/Users/frak/.pyenv/versions/3.6.5/lib/python3.6/site-packages/appJar/appjar.py", line 4319, in startContainer
    tab = self._getContainerProperty('container').addTab(title)
  File "/Users/frak/.pyenv/versions/3.6.5/lib/python3.6/site-packages/appJar/appjar.py", line 4752, in addTab
    self._configTabs()
  File "/Users/frak/.pyenv/versions/3.6.5/lib/python3.6/site-packages/appJar/appjar.py", line 4820, in _configTabs
    self.widgetStore[key][0].config(bg=self.inactiveBg, fg=self.inactiveFg, cursor=self.inactiveCursor)
  File "/Users/frak/.pyenv/versions/3.6.5/lib/python3.6/tkinter/__init__.py", line 1482, in configure
    return self._configure('configure', cnf, kw)
  File "/Users/frak/.pyenv/versions/3.6.5/lib/python3.6/tkinter/__init__.py", line 1473, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: bad cursor spec "pointinghand"
```

**Comment by frakman1** [comment]
I traced this error to this line:
https://github.com/jarvisteach/appJar/blob/0b59ce041da2197dcff3410e20f298676f1f7266/appJar/appjar.py#L4618

I changed `pointinghand` to `arrow` according to some information I found here:
https://www.tcl.tk/man/tcl8.4/TkCmd/cursors.html
specifically, this section:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/5826484/173229426-231ca203-84db-40ac-a7b1-6c28a0f5ea89.png">

This resolved the issue for me.
Putting this here so people searching for this error may one day find relief.
